channels:
  - conda-forge
  - defaults
dependencies:
  - boto
  - requests
  - matplotlib
  - python-ternary
  - basemap
  - numpy
  - pandas
  - periodictable
  - scipy
  - scikit-learn
  - pathlib
  - psutil
  - memory_profiler
